name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  
          EC2_USER: ubuntu                           
          EC2_HOST: ${{ secrets.EC2_HOST }}           
        run: |
          echo "${PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Transfer the build_and_deploy.sh script to the EC2 instance
          scp -i private_key.pem ./build_and_deploy.sh $EC2_USER@$EC2_HOST:~/app3/

          # SSH into the EC2 instance and run the script
          ssh -i private_key.pem $EC2_USER@$EC2_HOST << EOF
          cd ~/app3
          chmod +x build_and_deploy.sh
          ./build_and_deploy.sh deploy
          EOF 